image: alpine:latest

stages:
  - test
  - deploy

test:
  stage: test
  image: node:18-alpine
  script:
    - npm ci
    - npm run format
    - npm run lint
    - echo "Test stage completed successfully"
  only:
    - main

deploy_staging:
  stage: deploy
  script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ls -la ~/
    - pwd
    - echo "SSH_PRIVATE_KEY längd: ${#SSH_PRIVATE_KEY}"
    - echo "STAGING_HOST: $STAGING_HOST"
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ls -la ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - chmod 600 ~/.ssh/config
    - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@194.47.178.35 "echo 'SSH connection test'" || echo "SSH connection failed"
    - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@194.47.178.35 "cd ~/cashtrack && git pull origin main && docker-compose -f docker-compose.yml -f docker-compose.production.yml down && docker-compose -f docker-compose.yml -f docker-compose.production.yml up --build -d"
  only:
    - main