image: node:18-alpine

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npm ci
    - echo "Kör formatering med Prettier"
    - npm run format
    - echo "Kör linting"
    - npm run lint
    - echo "Tester av byggprocessen"
    - npm run build
    - echo "Test stage completed successfully"
  only:
    - main

deploy_staging:
  stage: deploy
  image: alpine:latest
  script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - chmod 600 ~/.ssh/config
    - echo "Connecting to $STAGING_HOST..."
    - ssh -i ~/.ssh/id_rsa ubuntu@$STAGING_HOST "cd ~/cashtrack && git pull origin main && docker-compose -f docker-compose.yml -f docker-compose.production.yml down && docker-compose -f docker-compose.yml -f docker-compose.production.yml up --build -d"
  only:
    - main