image: alpine:latest

stages:
  - test

test_ssh:
  stage: test
  script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    
    # Spara SSH-nyckeln med literal flaggan (-E) för att bevara radbrytningar
    - echo -E "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    
    # Se om nyckeln har innehåll
    - echo "Filstorlek i bytes:"
    - stat -c "%s" ~/.ssh/id_rsa
    
    # Kontrollera om variabeln har innehåll (utan att visa det)
    - echo "SSH_PRIVATE_KEY variabel längd:"
    - echo "$SSH_PRIVATE_KEY" | wc -c
    
    - echo "Testar anslutning:"
    - ssh -o StrictHostKeyChecking=no -vT ubuntu@194.47.178.35 "echo 'Test'"
  only:
    - main