version: '3.8'

services:
  nextjs:
    container_name: cashtrack-nextjs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mysql
    networks:
      - cashtrack-network

  mysql:
    container_name: cashtrack-mysql
    image: mysql:8
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-cashtrack}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
    networks:
      - cashtrack-network

volumes:
  mysql-data:

networks:
  cashtrack-network:
    driver: bridge
