version: '3.8'

services:
  nextjs:
    build:
      target: base
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:password@cashtrack-mysql:3306/cashtrack
      - JWT_SECRET=dev_secret
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USER=${SMTP_USER}
      - APP_URL=${APP_URL}
    restart: unless-stopped

  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=cashtrack
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
