version: '3.8'

services:
  nextjs:
    container_name: cashtrack-nextjs
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD:-password}@cashtrack-mysql:3306/${MYSQL_DATABASE:-cashtrack}
      - DIRECT_URL=${DIRECT_URL}
      - JWT_SECRET=${JWT_SECRET:-secure_production_secret}
    depends_on:
      - mysql
    networks:
      - cashtrack-network

  mysql:
    container_name: cashtrack-mysql
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-cashtrack}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
    networks:
      - cashtrack-network

  nginx:
    container_name: cashtrack-nginx
    image: nginx:alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    restart: always
    depends_on:
      - nextjs
    networks:
      - cashtrack-network

  certbot:
    container_name: cashtrack-certbot
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email jens.karlsson@hotmail.com --agree-tos --no-eff-email --force-renewal -d cashtrack.se -d www.cashtrack.se
    depends_on:
      - nginx
    networks:
      - cashtrack-network

volumes:
  mysql-data:

networks:
  cashtrack-network:
    driver: bridge